// // This file was automatically generated by the js2ts_converter.
// // Do not modify this file manually.

// var window = null;

// function _0x5cd844(e: any) {
//     var b: any = {
//         exports: {}
//     };
//     return e(b, b.exports), b.exports
// }

// let jsvmp = function (e: any, b: any, a: any) {
//     function f(e: any, b: any, a: any) {
//         return (f = function () {
//             if ("undefined" == typeof Reflect || !Reflect.construct || Reflect.construct.sham) return !1;
//             if ("function" == typeof Proxy) return !0;
//             try {
//                 return Date.prototype.toString.call(Reflect.construct(Date, [], function () {
//                 })), !0
//             } catch (e: any) {
//                 return !1
//             }
//         }() ? Reflect.construct : function (e: any, b: any, a: any) {
//             var f: any = [null];
//             f.push.apply(f, b);
//             var c: any = new (Function.bind.apply(e, f));
//             return a && function (e: any, b: any) {
//                 (Object.setPrototypeOf || function (e: any, b: any) {
//                     return e.__proto__ = b, e
//                 })(e, b)
//             }(c, a.prototype), c
//         }).apply(null, arguments)
//     }

//     function c(e: any) {
//         return function (e: any) {
//             if (Array.isArray(e)) {
//                 for (var b: any = 0, a: any = new Array(e.length); b < e.length; b++) a[b] = e[b];
//                 return a
//             }
//         }(e) || function (e: any) {
//             if (Symbol.iterator in Object(e) || "[object Arguments]" === Object.prototype.toString.call(e)) return Array.from(e)
//         }(e) || function () {
//             throw new TypeError("Invalid attempt to spread non-iterable instance")
//         }()
//     }

//     for (var r: any = [], t: any = 0, d: any = [], i: any = 0, n: any = function (e: any, b: any) {
//         var a: any = e[b++],
//             f: any = e[b],
//             c: any = parseInt("" + a + f, 16);
//         if (c >> 7 == 0) return [1, c];
//         if (c >> 6 == 2) {
//             var r: any = parseInt("" + e[++b] + e[++b], 16);
//             return c &= 63, [2, r = (c <<= 8) + r]
//         }
//         if (c >> 6 == 3) {
//             var t: any = parseInt("" + e[++b] + e[++b], 16),
//                 d: any = parseInt("" + e[++b] + e[++b], 16);
//             return c &= 63, [3, d = (c <<= 16) + (t <<= 8) + d]
//         }
//     }, s: any = function (e: any, b: any) {
//         var a: any = parseInt("" + e[b] + e[b + 1], 16);
//         return a > 127 ? -256 + a : a
//     }, o: any = function (e: any, b: any) {
//         var a: any = parseInt("" + e[b] + e[b + 1] + e[b + 2] + e[b + 3], 16);
//         return a > 32767 ? -65536 + a : a
//     }, l: any = function (e: any, b: any) {
//         var a: any = parseInt("" + e[b] + e[b + 1] + e[b + 2] + e[b + 3] + e[b + 4] + e[b + 5] + e[b + 6] + e[b + 7], 16);
//         return a > 2147483647 ? 0 + a : a
//     }, _ = any = function (e: any, b: any) {
//         return parseInt("" + e[b] + e[b + 1], 16)
//     }, x: any = function (e: any, b: any) {
//         return parseInt("" + e[b] + e[b + 1] + e[b + 2] + e[b + 3], 16)
//     }, u: any = u || this || window, h: any = (e.length, 0), p: any = "", y: any = h; y < h + 16; y++) {
//         var v: any = "" + e[y++] + e[y];
//         v = parseInt(v, 16), p += String.fromCharCode(v)
//     }
//     if ("HNOJ@?RC" != p) throw new Error("error magic number " + p);
//     parseInt("" + e[h += 16] + e[h + 1], 16), h += 8, t = 0;
//     for (var g: any = 0; g < 4; g++) {
//         var w: any = h + 2 * g,
//             A: any = parseInt("" + e[w++] + e[w], 16);
//         t += (3 & A) << 2 * g
//     }
//     h += 16;
//     var C: any = parseInt("" + e[h += 8] + e[h + 1] + e[h + 2] + e[h + 3] + e[h + 4] + e[h + 5] + e[h + 6] + e[h + 7], 16),
//         m: any = C,
//         S: any = h += 8,
//         z: any = x(e, h += C);
//     z[1], h += 4, r = {
//         p: [],
//         q: []
//     };
//     for (var B: any = 0; B < z; B++) {
//         for (var R: any = n(e, h), q: any = h += 2 * R[0], I: any = r.p.length, k: any = 0; k < R[1]; k++) {
//             var j: any = n(e, q);
//             r.p.push(j[1]), q += 2 * j[0]
//         }
//         h = q, r.q.push([I, r.p.length])
//     }
//     var O: any = {
//             5: 1,
//             6: 1,
//             70: 1,
//             22: 1,
//             23: 1,
//             37: 1,
//             73: 1
//         },
//         U: any = {
//             72: 1
//         },
//         D: any = {
//             74: 1
//         },
//         N: any = {
//             11: 1,
//             12: 1,
//             24: 1,
//             26: 1,
//             27: 1,
//             31: 1
//         },
//         J: any = {
//             10: 1
//         },
//         L: any = {
//             2: 1,
//             29: 1,
//             30: 1,
//             20: 1
//         },
//         T: any = [],
//         E: any = [];

//     function M(e: any, b: any, a: any) {
//         for (var f: any = b; f < b + a;) {
//             var c: any = _(e, f);
//             T[f] = c, f += 2, U[c] ? (E[f] = s(e, f), f += 2) : O[c] ? (E[f] = o(e, f), f += 4) : D[c] ? (E[f] = l(e, f), f += 8) : N[c] ? (E[f] = _(e, f), f += 2) : J[c] ? (E[f] = x(e, f), f += 4) : L[c] && (E[f] = x(e, f), f += 4)
//         }
//     }
//     // ... (previous code)

//     return F(e, S, m / 2, [], b, a);

//     function P(e: any, b: any, a: any, n: any, h: any, p: any, y: any, v: any) {
//         null == p && (p = this);
//         var g: any, w: any, A: any, C: any, m: any = [],
//             S: any = 0;
//         y && (w = y);
//         var z: any, B: any, R: any = b,
//             q: any = R + 2 * a;
//         if (!v)
//             for (; R < q;) {
//                 var I: any = parseInt("" + e[R] + e[R + 1], 16);
//                 R += 2;
//                 var j: any = 3 & (z = 13 * I % 241);
//                 if (z >>= 2, j < 1)
//                     if (j = 3 & z, z >>= 2, j < 1) {
//                         if ((j = z) < 1) return [1, m[S--]];
//                         j < 5 ? (w = m[S--], m[S] = m[S] * w) : j < 7 ? (w = m[S--], m[S] = m[S] != w) : j < 14 ? (A = m[S--], C = m[S--], (j = m[S--]).x === P ? j.y >= 1 ? m[++S] = F(e, j.c, j.l, A, j.z, C, null, 1) : (m[++S] = F(e, j.c, j.l, A, j.z, C, null, 0), j.y++) : m[++S] = j.apply(C, A)) : j < 16 && (B = o(e, R), (g = function b() {
//                             var a: any = arguments;
//                             return b.y > 0 || b.y++, F(e, b.c, b.l, a, b.z, this, null, 0)
//                         }).c = R + 4, g.l = B - 2, g.x = P, g.y = 0, g.z = h, m[S] = g, R += 2 * B - 2)
//                     } else if (j < 2) (j = z) > 8 ? (w = m[S--], m[S] = typeof w) : j > 4 ? m[S -= 1] = m[S][m[S + 1]] : j > 2 && (A = m[S--], (j = m[S]).x === P ? j.y >= 1 ? m[S] = F(e, j.c, j.l, [A], j.z, C, null, 1) : (m[S] = F(e, j.c, j.l, [A], j.z, C, null, 0), j.y++) : m[S] = j(A));
//                     else if (j < 3) {
//                         if ((j = z) < 9) {
//                             for (w = m[S--], B = x(e, R), j = "", k = r.q[B][0]; k < r.q[B][1]; k++) j += String.fromCharCode(t ^ r.p[k]);
//                             R += 4, m[S--][j] = w
//                         } else if (j < 13) throw m[S--]
//                     } else (j = z) < 1 ? m[++S] = null : j < 3 ? (w = m[S--], m[S] = m[S] >= w) : j < 12 && (m[++S] = void 0);
//                 else if (j < 2)
//                     if (j = 3 & z, z >>= 2, j < 1)
//                         if ((j = z) < 5) {
//                             B = o(e, R);
//                             try {
//                                 if (d[i][2] = 1, 1 == (w = P(e, R + 4, B - 3, [], h, p, null, 0))[0]) return w
//                             } catch (b: any) {
//                                 if (d[i] && d[i][1] && 1 == (w = P(e, d[i][1][0], d[i][1][1], [], h, p, b, 0))[0]) return w
//                             } finally {
//                                 if (d[i] && d[i][0] && 1 == (w = P(e, d[i][0][0], d[i][0][1], [], h, p, null, 0))[0]) return w;
//                                 d[i] = 0, i--
//                             }
//                             R += 2 * B - 2
//                         } else j < 7 ? (B = _(e, R), R += 2, m[S -= B] = 0 === B ? new m[S] : f(m[S], c(m.slice(S + 1, S + B + 1)))) : j < 9 && (w = m[S--], m[S] = m[S] & w);
//                     else if (j < 2)
//                         if ((j = z) > 12) m[++S] = s(e, R), R += 2;
//                         else if (j > 10) w = m[S--], m[S] = m[S] << w;
//                         else if (j > 8) {
//                             for (B = x(e, R), j = "", k = r.q[B][0]; k < r.q[B][1]; k++) j += String.fromCharCode(t ^ r.p[k]);
//                             R += 4, m[S] = m[S][j]
//                         } else j > 6 && (A = m[S--], w = delete m[S--][A]);
//                     else if (j < 3) (j = z) < 2 ? m[++S] = w : j < 11 ? (w = m[S -= 2][m[S + 1]] = m[S + 2], S--) : j < 13 && (w = m[S], m[++S] = w);
//                     else if ((j = z) > 12) m[++S] = p;
//                     else if (j > 5) w = m[S--], m[S] = m[S] !== w;
//                     else if (j > 3) w = m[S--], m[S] = m[S] / w;
//                     else if (j > 1) {
//                         if ((B = o(e, R)) < 0) {
//                             v = 1, M(e, b, 2 * a), R += 2 * B - 2;
//                             break
//                         }
//                         R += 2 * B - 2
//                     } else j > -1 && (m[S] = !m[S]);
//                 else if (j < 3)
//                     if (j = 3 & z, z >>= 2, j < 1) (j = z) > 13 ? (m[++S] = o(e, R), R += 4) : j > 11 ? (w = m[S--], m[S] = m[S] >> w) : j > 9 ? (B = _(e, R), R += 2, h[B] = w) : j > 7 ? (B = x(e, R), R += 4, A = S + 1, m[S -= B - 1] = B ? m.slice(S, A) : []) : j > 0 && (w = m[S--], m[S] = m[S] > w);
//                     else if (j < 2) (j = z) > 12 ? (w = m[S - 1], A = m[S], m[++S] = w, m[++S] = A) : j > 3 ? (w = m[S--], m[S] = m[S] == w) : j > 1 ? (w = m[S--], m[S] = m[S] + w) : j > -1 && (m[++S] = u);
//                     else if (j < 3) {
//                         if ((j = z) > 13) m[++S] = !1;
//                         // ... (previous code)

// else if (j > 6) {
//     for (B = x(e, R), j = "", k = r.q[B][0]; k < r.q[B][1]; k++) j += String.fromCharCode(t ^ r.p[k]);
//     R += 4, m[S] = m[S][j] = w
// } else j > 4 ? (B = o(e, R), R += 4, m[S] = m[S] >>> B) : j > 2 && (w = m[S--], m[S] = m[S] < w);
// else if (j < 2)
//     if (j = z, j > 12) m[++S] = w;
//     else if (j > 5) w = m[S--], m[S] = m[S] !== w;
//     else if (j > 3) w = m[S--], m[S] = m[S] / w;
//     else if (j > 1) {
//         if ((B = o(e, R)) < 0) {
//             v = 1, M(e, b, 2 * a), R += 2 * B - 2;
//             break
//         }
//         R += 2 * B - 2
//     } else j > -1 && (m[S] = !m[S]);
// else if (j < 3)
//     if (j = 3 & z, z >>= 2, j < 1) (j = z) > 13 ? (m[++S] = o(e, R), R += 4) : j > 11 ? (w = m[S--], m[S] = m[S] << w) : j > 9 ? (B = _(e, R), R += 2, h[B] = w) : j > 7 ? (B = x(e, R), R += 4, A = S + 1, m[S -= B - 1] = B ? m.slice(S, A) : []) : j > 0 && (w = m[S--], m[S] = m[S] > w);
//     else if (j < 2) (j = z) > 12 ? (w = m[S - 1], A = m[S], m[++S] = w, m[++S] = A) : j > 3 ? (w = m[S--], m[S] = m[S] == w) : j > 1 ? (w = m[S--], m[S] = m[S] + w) : j > -1 && (m[++S] = u);
//     else if (j < 3) {
//         if ((j = z) > 13) m[++S] = !1;
//         else if (j > 6) {
//             for (B = x(e, R), j = "", k = r.q[B][0]; k < r.q[B][1]; k++) j += String.fromCharCode(t ^ r.p[k]);
//             R += 4, m[S] = m[S][j] = w
//         } else j > 4 ? (B = o(e, R), R += 4, m[S] = m[S] >>> B) : j > 2 && (w = m[S--], m[S] = m[S] < w);
//     } else if (j < 2)
//         if (j = z, j > 12) m[++S] = w;
//         else if (j > 5) w = m[S--], m[S] = m[S] !== w;
//         else if (j > 3) w = m[S--], m[S] = m[S] / w;
//         else if (j > 1) {
//             if ((B = o(e, R)) < 0) {
//                 v = 1, M(e, b, 2 * a), R += 2 * B - 2;
//                 break
//             }
//             R += 2 * B - 2
//         } else j > -1 && (m[S] = !m[S]);
//     else if (j < 3)
//         if (j = 3 & z, z >>= 2, j < 1) (j = z) > 13 ? (m[++S] = o(e, R), R += 4) : j > 11 ? (w = m[S--], m[S] = m[S] << w) : j > 9 ? (B = _(e, R), R += 2, h[B] = w) : j > 7 ? (B = x(e, R), R += 4, A = S + 1, m[S -= B - 1] = B ? m.slice(S, A) : []) : j > 0 && (w = m[S--], m[S] = m[S] > w);
//         else if (j < 2) (j = z) > 12 ? (w = m[S - 1], A = m[S], m[++S] = w, m[++S] = A) : j > 3 ? (w = m[S--], m[S] = m[S] == w) : j > 1 ? (w = m[S--], m[S] = m[S] + w) : j > -1 && (m[++S] = u);
//         else if (j < 3) {
//             if ((j = z) > 13) m[++S] = !1;
//             else if (j > 6) {
//                 for (B = x(e, R), j = "", k = r.q[B][0]; k < r.q[B][1]; k++) j += String.fromCharCode(t ^ r.p[k]);
//                 R += 4, m[S] = m[S][j] = w
//             } else j > 4 ? (B = o(e, R), R += 4, m[S] = m[S] >>> B) : j > 2 && (w = m[S--], m[S] = m[S] < w);
//         } else if (j < 2)
//             if (j = z, j > 12) m[++S] = w;
//             else if (j > 5) w = m[S--], m[S] = m[S] !== w;
//             else if (j > 3) w = m[S--], m[S] = m[S] / w;
//             else if (j > 1) {
//                 if ((B = o(e, R)) < 0) {
//                     v = 1, M(e, b, 2 * a), R += 2 * B - 2;
//                     break
//                 }
//                 R += 2 * B - 2
//             } else j > -1 && (m[S] = !m[S]);
//         else if (j < 3)
//             if (j = 3 & z, z >>= 2, j < 1) (j = z) > 13 ? (m[++S] = o(e, R), R += 4) : j > 11 ? (w = m[S--], m[S] = m[S] << w) : j > 9 ? (B = _(e, R), R += 2, h[B] = w) : j > 7 ? (B = x(e, R), R += 4, A = S + 1, m[S -= B - 1] = B ? m.slice(S, A) : []) : j > 0 && (w = m[S--], m[S] = m[S] > w);
//             else if (j < 2) (j = z) > 12 ? (w = m[S - 1], A = m[S], m[++S] = w, m[++S] = A) : j > 3 ? (w = m[S--], m[S] = m[S] == w) : j > 1 ? (w = m[S--], m[S] = m[S] + w) : j > -1 && (m[++S] = u);
//             else if (j < 3) {
//                 if ((j = z) > 13) m[++S] = !1;
//                 else if (j > 6) {
//                     for (B = x(e, R), j = "", k = r.q[B][0]; k < r.q[B][1]; k++) j += String.fromCharCode(t ^ r
                            

// // function get_web_id(): string {
// //   return (function e(t: number): string {
// //     return t
// //       ? ((t ^ (16 * Math.random())) >> (t / 4)).toString(10)
// //       : ([1e7] + -1e3 + -4e3 + -8e3 + -1e11).replace(/[018]/g, e);
// //   }().replace(/-/g, '').slice(0, 19);
// // }

// const ua =
//   'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36';
// const urlPath =
//   'https://www.douyin.com/aweme/v1/web/aweme/post/?device_platform=webapp&aid=6383&channel=channel_pc_web&sec_user_id=MS4wLjABAAAAW9FWcqS7RdQAWPd2AA5fL_ilmqsIFUCQ_Iym6Yh9_cUa6ZRqVLjVQSUjlHrfXY1Y&max_cursor=0&locate_query=false&show_live_replay_strategy=1&need_time_list=1&time_list_query=0&whale_cut_token=&cut_version=1&count=18&publish_video_strategy_type=2&pc_client_type=1&version_code=170400&version_name=17.4.0&cookie_enabled=true&screen_width=1920&screen_height=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Edge&browser_version=122.0.0.0&browser_online=true&engine_name=Blink&engine_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&device_memory=8&platform=PC&downlink=10&effective_type=4g&round_trip_time=50&webid=7335414539335222835&msToken=p9Y7fUBuq9DKvAuN27Peml6JbaMqG2ZcXfFiyDv1jcHrCN00uidYqUgSuLsKl1onC-E_n82m-aKKYE0QGEmxIWZx9iueQ6WLbvzPfqnMk4GBAlQIHcDzxb38FLXXQxAm';

// const xbs = sign(urlPath, ua);
// console.log(xbs);
