export declare const oldDouyinParams: {
    device_platform: string;
    aid: string;
    channel: string;
    cookie_enabled: string;
    browser_language: string;
    browser_platform: string;
    browser_name: string;
    browser_version: string;
    browser_online: string;
    engine_name: string;
    os_name: string;
    os_version: string;
    engine_version: string;
    platform: string;
    screen_width: string;
    screen_height: string;
};
export declare const newDouyinParams: {
    device_platform: string;
    aid: string;
    channel: string;
    pc_client_type: string;
    version_code: string;
    version_name: string;
    cookie_enabled: string;
    screen_width: string;
    screen_height: string;
    browser_language: string;
    browser_platform: string;
    browser_name: string;
    browser_version: string;
    browser_online: string;
    engine_name: string;
    engine_version: string;
    os_name: string;
    os_version: string;
    cpu_core_num: string;
    device_memory: string;
    platform: string;
};
export declare const MACDouYinParams: {
    device_platform: string;
    aid: number;
    channel: string;
    detail_list: number;
    source: number;
    main_billboard_count: number;
    pc_client_type: number;
    version_code: string;
    version_name: string;
    cookie_enabled: boolean;
    screen_width: number;
    screen_height: number;
    browser_language: string;
    browser_platform: string;
    browser_name: string;
    browser_version: string;
    browser_online: boolean;
    engine_name: string;
    engine_version: string;
    os_name: string;
    os_version: string;
    cpu_core_num: number;
    device_memory: string;
    platform: string;
    webid: string;
};
export declare function getDouyinDetailParams(type: string, awemeID: string): Promise<object>;
